export * from './authorization/authorization.js';
export * from './registration/registration.js';
export * from './bookings/bookings.js';
export * from './user-bookings/user-bookings.js';
export * from '../component/error404/error404.js';
export * from './about-us/about-us.js';
export * from './main/main.js';
export * from './room/room.js';
export * from './rooms/rooms.js';
